root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd"
  bin = "main"
  full_bin = "tmp/main"
  include_ext = ["go"]
  exclude = [
      "go.mod",
      "go.sum",
      ".git",
      ".DS_Store",
      "*.log"
  ]
  exclude_dir = ["vendor", "tmp"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"

[misc]
  clean_on_exit = true